INSERT INTO permissions (name, slug, description) VALUES
    ('View Users', 'users.view', 'Melihat daftar pengguna'),
    ('Create Users', 'users.create', 'Membuat pengguna baru'),
    ('Update Users', 'users.update', 'Mengubah data pengguna'),
    ('Delete Users', 'users.delete', 'Menghapus pengguna'),
    ('View Patients', 'patients.view', 'Melihat data pasien'),
    ('Create Patients', 'patients.create', 'Membuat data pasien'),
    ('Update Patients', 'patients.update', 'Mengubah data pasien'),
    ('Delete Patients', 'patients.delete', 'Menghapus data pasien'),
    ('View Doctors', 'doctors.view', 'Melihat data dokter'),
    ('Create Doctors', 'doctors.create', 'Membuat data dokter'),
    ('Update Doctors', 'doctors.update', 'Mengubah data dokter'),
    ('Delete Doctors', 'doctors.delete', 'Menghapus data dokter'),
    ('View Medical Records', 'medical_records.view', 'Melihat rekam medis'),
    ('Create Medical Records', 'medical_records.create', 'Membuat rekam medis'),
    ('Update Medical Records', 'medical_records.update', 'Mengubah rekam medis'),
    ('View Medicines', 'medicines.view', 'Melihat data obat'),
    ('Create Medicines', 'medicines.create', 'Membuat data obat'),
    ('Update Medicines', 'medicines.update', 'Mengubah data obat'),
    ('View Queue', 'queue.view', 'Melihat antrian'),
    ('Create Queue', 'queue.create', 'Membuat antrian'),
    ('Update Queue', 'queue.update', 'Mengubah antrian'),
    ('View Billing', 'billing.view', 'Melihat tagihan'),
    ('Create Billing', 'billing.create', 'Membuat transaksi tagihan'),
    ('Update Billing', 'billing.update', 'Mengubah transaksi tagihan'),
    ('View Reports', 'reports.view', 'Melihat laporan')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description);
